In [1]:
import numpy as np

In [7]:
a = np.eye(4)
a *= 10

a

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[3, 3, 3], [3, 3, 3], [3, 3, 3]])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a @ b)
print(a ** 2)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]
[[18 18 18]
 [45 45 45]
 [72 72 72]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [57]:
a = np.arange(50)
a += 1

np.random.shuffle(a)

test_data = a[10:]
train_data = a[:10]

print(f"train_data = {train_data}")
print(f"test_data = {test_data}")

train_data = [ 9 24  6 46 28 34  4 37 17 26]
test_data = [11 45 18 19 40 20 36  5 42 15 41 27 35 23 32 31 49 44 29 22 38 33 13 39
 50 30 43 16  3 14 48  1 47 12 21  7 10  2  8 25]


In [22]:
a = np.arange(10)

print(f"a = {a}")

a = a.reshape(2, 5)

print(f"a = {a}")

aT = a.T

print(aT)

a = [0 1 2 3 4 5 6 7 8 9]
a = [[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
