In [1]:
import numpy as np

## 행렬방정식 (연립)

In [2]:
A = np.random.randn(4, 4)
B = np.random.randn(4, 4)

X1 = np.linalg.inv(A)
X2 = B @ np.linalg.inv(A)

res1 = A@X1 - B
res2 = A@X2 - B

np.around(res1, 5), np.around(res2, 5)

(array([[ 1.1416 ,  0.33464, -0.01417, -0.01305],
        [ 0.86023,  1.19952,  0.76382,  0.99167],
        [-0.39893, -0.81631, -0.07503, -0.18584],
        [ 0.67975, -1.5087 ,  1.39182,  0.96588]]),
 array([[-0.26766, -0.98167,  2.41115,  0.73853],
        [ 0.37447,  0.03451,  1.42098,  1.02658],
        [-2.10585, -0.44963,  0.47244, -0.39697],
        [ 0.34074,  1.86992, -1.4276 , -0.23928]]))

## RREF -> 기약 행 사다리꼴

In [3]:
import sympy as sym

M = np.array([[1, 1, 4], [-1/2, 1, 2]])
symMat = sym.Matrix(M)

#RREF

symMat.rref()[0]

Matrix([
[1, 0, 1.33333333333333],
[0, 1, 2.66666666666667]])

## 실습

In [5]:
M = np.array([[3, 4, -5, 11], [1, 2, -10, 1], [2, 9, -5, 13]])
symMat = sym.Matrix(M)

symMat.rref()[0]

Matrix([
[1, 0, 0,   3],
[0, 1, 0,   1],
[0, 0, 1, 2/5]])

## LU

In [ ]:
import scipy
import scipy.linalg

A = np.array([[2, 2, 4], [1, 0, 3], [2, 1, 2]])

P, L, U = scipy.linalg.lu(A)
#치환 행렬 : P
print(L, U)


[[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.  1.  1. ]] [[ 2.  2.  4.]
 [ 0. -1.  1.]
 [ 0.  0. -3.]]


In [17]:
print(P.T@A)
print(L@U)

print(A)
print(P@L@U)

print(P)
print(P.T == P)

[[2. 2. 4.]
 [1. 0. 3.]
 [2. 1. 2.]]
[[2. 2. 4.]
 [1. 0. 3.]
 [2. 1. 2.]]
[[2 2 4]
 [1 0 3]
 [2 1 2]]
[[2. 2. 4.]
 [1. 0. 3.]
 [2. 1. 2.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## 최소제곱법

In [18]:
import numpy as np

# A 행렬과 b 벡터 정의
A = np.array([[1, 1], [1, 2], [1, 3]])  # 예제 행렬 (3x2)
b = np.array([1, 2, 2])                # 예제 벡터 (3x1)

# 최소제곱 해 (x_hat) 계산
A_T = A.T
x_hat = np.linalg.inv(A_T @ A) @ (A_T @ b)

# b를 기준 성분과 수직 성분으로 분해
b_projected = A @ x_hat  # A의 기저를 따라가는 성분
b_residual = b - b_projected  # A의 기저에 수직인 성분

# 결과 출력
print("x_hat (최소제곱 해):", x_hat)
print("b_projected (기준 성분):", b_projected)
print("b_residual (수직 성분):", b_residual)


x_hat (최소제곱 해): [0.66666667 0.5       ]
b_projected (기준 성분): [1.16666667 1.66666667 2.16666667]
b_residual (수직 성분): [-0.16666667  0.33333333 -0.16666667]


## QR분해

In [ ]:
A = np.array([[1, 3, 5], [1, 1, 0], [1, 1, 2], [1, 3, 3]])
B = np.array([[3, 5, 7, -3]]).T

print(A, B)

Q, R = np.linalg.qr(A)

# 최소제곱 해 계산
Q_T_b = Q.T @ B
x_hat = np.linalg.solve(R, Q_T_b)  # 상삼각 행렬 R에 대한 해 계산

# 결과 출력
print("Q 행렬:\n", Q)
print("R 행렬:\n", R)
print("x_hat (최소제곱 해):", x_hat)

[[1 3 5]
 [1 1 0]
 [1 1 2]
 [1 3 3]] [[ 3]
 [ 5]
 [ 7]
 [-3]]
Q 행렬:
 [[-0.5  0.5 -0.5]
 [-0.5 -0.5  0.5]
 [-0.5 -0.5 -0.5]
 [-0.5  0.5  0.5]]
R 행렬:
 [[-2. -4. -5.]
 [ 0.  2.  3.]
 [ 0.  0. -2.]]
x_hat (최소제곱 해): [[10.]
 [-6.]
 [ 2.]]
