In [35]:
import numpy as np

In [23]:
def norm(v) :
    return np.linalg.norm(v)

In [29]:
v1 = np.array([1, 2, 3])
v2 = np.array([2, 4, 5])

def getPearson(v1, v2) :
    # return np.norm(v1 - v1.mean(), v2 - v2.mean()) \ 
    return (v1 - v1.mean()).T @ (v2 - v2.mean()) \
        / (np.linalg.norm(v1 - v1.mean()) * (np.linalg.norm(v2 - v2.mean())))

print(getPearson(v1, v2))

print(np.corrcoef(v1, v2))

0.9999999999999998
[[1. 1.]
 [1. 1.]]


In [30]:
v1 = np.array([1, 2, 3])
v2 = np.array([2, 4, 5])

cos = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

cos

0.9960238411119946


In [32]:
s0 = np.array([1, 0])
s1 = np.array([0, 1])

p = 3 * s0 + 1 * s1
q = -6 * s0 + 2 * s1

p, q

(array([3, 1]), array([-6,  2]))

In [34]:
t0 = np.array([3, 1])
t1 = np.array([-3, 1])

p = 1 * t0 + 0 * t1
q = 0 * t0 + 2 * t1

p, q

(array([3, 1]), array([-6,  2]))