In [1]:
import numpy as np

In [7]:
A = np.arange(60).reshape(6, 10)

A

sub = A[1:3:1, 0:4:1] #??

sub

array([[10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [8]:
Mrows = 4
Mcols = 6

A = np.random.randn(Mrows, Mcols)

A

array([[-1.03589991, -0.78840988,  0.51618621,  0.01926533, -1.98359521,
         0.35308667],
       [-0.58585028, -0.76179627, -1.82596153, -1.28352374,  0.02895851,
         0.28669222],
       [-0.80050085, -0.43812109, -1.46093277, -0.35724818, -0.66212997,
         0.84681548],
       [ 0.00862225, -1.68824282,  0.40909783, -0.35942947, -1.64724156,
        -0.81747448]])

In [9]:
a = np.array([1, 2, 3])

da = np.diag(a)

print(a)
print(da)

print("\n\n\n")

b = np.arange(9).reshape(3, 3)
db = np.diag(b)

print(b)
print(db)

[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]




[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]


In [ ]:
a =np.arange(25).reshape(5, 5)

print(a)
print(np.triu(a))
print(np.tril(a))