In [40]:
import numpy as np

In [39]:
b = np.arange(12).reshape(3,4)

def calcSymMat(x) :
    return x.T @ x

print(calcSymMat(b))

[[ 80  92 104 116]
 [ 92 107 122 137]
 [104 122 140 158]
 [116 137 158 179]]
