In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [13]:
np.set_printoptions(precision=6, suppress=False)

Q1 = np.array([[1, -1], [1, 1]]) / np.sqrt(2)
Q2 = np.array([[1, 2, 2], [2, 1, -2], [-2, 2, -1]]) / 3

print(np.around(Q1.T @ Q1))
print(np.around(Q2.T @ Q2))

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [174]:
A = np.random.randn(3, 3)
#print(A)

def para(t, r) :
    return r * (t.dot(r) / r.dot(r))

def orth(t, para) :
    return t - para

#print(orth(t, para(t, r)))

def GS(A) :
    """
    v0 = A[:, 0]
    v1 = A[:, 1]
    v2 = A[:, 2]

    Q = np.zeros((3, 3))

    Q[0, :] = v0
    Q[1, :] = v1 - np.dot(Q[1, :], Q[0, :]) / np.dot(Q[0, :], Q[0, :]) * Q[0, :]
    Q[2, :] = v2 - np.dot(Q[2, :], Q[0, :]) / np.dot(Q[0, :], Q[0, :]) * Q[0, :]
    Q[2, :] = Q[2, :] - np.dot(Q[2, :], Q[1, :]) / np.dot(Q[1, :], Q[1, :]) * Q[1, :]

    Q[0, :] = Q[0, :] / np.linalg.norm(Q[0, :])
    Q[1, :] = Q[1, :] / np.linalg.norm(Q[1, :])
    Q[2, :] = Q[2, :] / np.linalg.norm(Q[2, :])

    Q = Q.T
    """

def getGS(m):
    r, c = 3, 3
    Q = np.zeros((r,c))
    for i in range(c):
        Q[:,i] = m[:,i]
        for j in range(i):
            q = Q[:,j]
            Q[:,i]=Q[:,i] - np.dot(Q[:,i],q)/np.dot(q,q)*q
        Q[:,i] = Q[:,i] / np.linalg.norm(Q[:,i])      

    return Q

Q = getGS(A)

print(np.linalg.norm(Q[:, 0]))
print(np.linalg.norm(Q[:, 1]))
print(np.linalg.norm(Q[:, 2]))

print(Q[:, 0].T @ Q[:, 0])
print(Q[:, 1].T @ Q[:, 1])
print(Q[:, 2].T @ Q[:, 2])

print(Q.T@Q)


1.0
1.0
1.0
1.0
1.0
1.0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
