In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.random.randint(-3, 4, (3, 3))
A = A.T @ A

L, V = np.linalg.eig(A)

print(np.dot(V[:,0], V[:,1]))
print(np.dot(V[:,0], V[:,2]))
print(np.dot(V[:,1], V[:,2]))

1.3331058464580605e-16
-2.8280776216404284e-17
-2.764167583584017e-17


In [8]:
print(A)

[[ 2  5 -1]
 [ 5 13 -1]
 [-1 -1 14]]


In [27]:
B = np.random.randn(3, 3)
B = B.T @ A

LL, VV = np.linalg.eig(B)
L, V = np.linalg.eig(np.linalg.inv(B))

print(VV - V)
print(np.sort(np.abs(VV)))
print(np.sort(np.abs(V)))

print(np.around(np.sort(LL), 2))
print(np.around(np.sort(1 / L), 2))

[[-6.03987160e-02  1.80738503e+00  1.42663659e-14]
 [ 7.99799720e-01  8.95478025e-02  7.41767758e-15]
 [-2.39790624e-01 -1.56567539e-01 -7.54951657e-15]]
[[0.45145772 0.87349316 0.93389187]
 [0.04618636 0.35512596 0.44467376]
 [0.04161154 0.19817908 0.89109638]]
[[0.45145772 0.87349316 0.93389187]
 [0.04618636 0.35512596 0.44467376]
 [0.04161154 0.19817908 0.89109638]]
[-20.25  -0.04  21.  ]
[-20.25  -0.04  21.  ]


In [10]:
A = np.random.randn(5, 5)
A = A.T@A

el0, ec0 = np.linalg.eig(A)
el1, ec1 = np.linalg.eig(np.linalg.inv(A))

print(np.around(ec0, 2))
print(ec1.round(2))

np.set_printoptions(suppress=True)

print(ec0 - ec1)
print(np.sort(np.abs(ec0)))
print(np.sort(np.abs(ec1)))
print(np.around(np.sort(el0), 2))
print(np.around(np.sort(1 / el1), 2))

[[-0.52 -0.34  0.74 -0.19  0.15]
 [-0.46  0.69  0.15  0.52 -0.11]
 [ 0.25 -0.33  0.1   0.73  0.53]
 [ 0.57  0.51  0.51 -0.25  0.3 ]
 [-0.35  0.2  -0.39 -0.3   0.77]]
[[ 0.19 -0.15 -0.74 -0.52 -0.34]
 [-0.52  0.11 -0.15 -0.46  0.69]
 [-0.73 -0.53 -0.1   0.25 -0.33]
 [ 0.25 -0.3  -0.51  0.57  0.51]
 [ 0.3  -0.77  0.39 -0.35  0.2 ]]
[[-0.71419984 -0.18941755  1.47975575  0.33549836  0.49663054]
 [ 0.06142397  0.57880491  0.30222138  0.98328625 -0.80541371]
 [ 0.98129188  0.20670244  0.20317447  0.48820737  0.85752782]
 [ 0.31777796  0.80495762  1.02761837 -0.82390251 -0.21034566]
 [-0.64979158  0.96872246 -0.78848322  0.05854238  0.570147  ]]
[[0.15360649 0.18935074 0.34302405 0.5248491  0.73987787]
 [0.1133044  0.15111069 0.46093114 0.52235511 0.69210931]
 [0.10158723 0.24654225 0.32541269 0.53211513 0.73474963]
 [0.25306228 0.29730598 0.50765164 0.51380918 0.57084023]
 [0.19928773 0.2956246  0.35416698 0.39424161 0.76943473]]
[[0.15360649 0.18935074 0.34302405 0.5248491  0.73987787]
 [0