In [54]:
import numpy as np

In [6]:
v = np.array([[1, 2, 3]]).T
n = np.array([[4, 5]])

print(v, n)

print(v + n)

print((v + n).shape)

[[1]
 [2]
 [3]] [[4 5]]
[[5 6]
 [6 7]
 [7 8]]
(3, 2)


In [26]:
t = np.array([3, 4])
r = np.array([1, 2])

proj = r * (np.dot(t, r) / np.dot(r, r))
fck = t - proj


print(proj + fck)
print(np.dot(fck, proj))

[3. 4.]
-1.9184653865522706e-15


In [19]:
pp = r * (t @ r) / (r @ r)
ff = t - pp
print(ff @ pp)

-1.9184653865522706e-15


In [53]:
v1 = np.array([1, 2, 3])
v2 = np.array([2, 4, 5])

def myCorrCoef(x, y) :
    return np.dot(x - np.mean(x), y - np.mean(y)) / (np.linalg.norm(x - np.mean(x)) * np.linalg.norm(y - np.mean(y)))

def cosCoef(x, y) :
    return np.dot(x, y) / (np.linalg.norm(x) * np.linalg.norm(y))

#print(np.corrcoef(v1, v2))

print(myCorrCoef(v1, v2))

print(cosCoef(v1, v2))

0.9819805060619655
0.9960238411119946


In [74]:
A = np.arange(60).reshape(6, 10)

sub = A[1:4:1, 0:5:1]

sub

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [76]:
a = np.array([[2, 3, 4], [1, 2, 4]])
b = np.array([[0, 3, 1], [-1, -4, 2]])

print(a + b)

[[ 2  6  5]
 [ 0 -2  6]]


In [77]:
a = np.array([[4, 5, 1], [0, 1, 11], [4, 9, 7]])

a + np.eye(len(a)) * 6

array([[10.,  5.,  1.],
       [ 0.,  7., 11.],
       [ 4.,  9., 13.]])

In [ ]:
A = np.arange(60).reshape(6, 10)

sub = A[1:4:1, 0:5:1]

sub

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [82]:
import matplotlib.pyplot as plt
import numpy as np

M = np.array([[2, 3], [2, 1]])
x = np.array([[1, 1.5]]).T
Mx = M @ x

plt.figure(figsize=(6, 6))
plt.plot([0, x[0, 0]], [0, x[1, 0]], '-.', linewidth=4, color=[0.0, 0.5, 0.7], label='x')
plt.plot([0, Mx[0, 0]], [0, Mx[1, 0]], '--', linewidth=3, color=[0.3, 0.3, 0.3], label='Mx')

plt.xlim([-7, 7])
plt.ylim([-7, 7])
plt.legend()  # 범례
plt.grid()
plt.show()
